name: Call Supabase Edge Function every 24 hours

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC (midnight) every day
  workflow_dispatch:       # Allows manual trigger from the Actions tab

jobs:
  call-function:
    runs-on: ubuntu-latest
    steps:
      - name: Call Edge Function
        run: |
          curl -X GET "https://vgjbljjluvlexargpigo.supabase.co/functions/v1/schedule-instagram-sync"
